# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  # prometheus.yml
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Kubernetes node exporter
      - job_name: 'kubernetes-node-exporter'
        scheme: http
        static_configs:
          - targets: ['node-exporter.kube-system:9100']

      # Flask application
      - job_name: 'flask-app'
        scheme: http
        static_configs:
          - targets: ['flask-app-service:8085']
