# Grafana ConfigMap for datasource configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: default
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
      editable: true
