apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system # Or your monitoring namespace
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app.kubernetes.io/name: node-exporter
